### ISSUE TITLE
.env.example is missing

### ISSUE THREAD

**Issue by gh640** [google-gemini/gemini-api-quickstart#7]
### Description of the bug:

The instruction "Setup" in README says `cp .env.example .env` but `.env.example` doesn't exist yet.

![image](https://github.com/user-attachments/assets/cb0b2a66-54c3-4744-abbb-273e33f12949)

## Expected behavior

`.env.example` exists with the following content:

```text
GOOGLE_API_KEY=
```

Or, the instruction says "Create an empty `.env` file and add your API key to it like:

```text
GOOGLE_API_KEY=...
```

**Comment by logankilpatrick** [comment]
Thank you! Merged the PR.
